# This is sourced to shell scripts.
# spaces and sections are handled with a function but keep spaces minimal, just in case.

[settings]
local_ip=127.0.0.1
listen_port=9092

# SSH/SSL credentials
[ssh]
host=ssl-sg1.hostip.co
username=fastssh.com-phoenix
password=pass123
port=443

[sni]
# example: facebook.com, zoom.us
server_name=zoom.us
