# This is sourced to shell scripts.
# spaces and ini sections are handled with a function but keep spaces minimal, just in case.

[settings]
local_ip=127.0.0.1
listen_port=9092

# SSH/SSL credentials
[ssh]
host= <ssh host>
username= <ssh username>
password= <ssh password>
port= <ssh port>

[sni]
# example: facebook.com, zoom.com
server_name=zoom.com
